"""Fix team hierarchy foreign key constraint

Revision ID: f49aee6af5b2
Revises: 8f946a078a8f
Create Date: 2025-08-10 02:44:23.149679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49aee6af5b2'
down_revision: Union[str, Sequence[str], None] = '8f946a078a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member_profiles_management', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('team_member_profiles_management', sa.Column('email', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member_profiles_management', 'email')
    op.drop_column('team_member_profiles_management', 'name')
    # ### end Alembic commands ###
